import SwiftUI

/// Dashboard card for Claude subscription usage windows.
///
/// Reads a local snapshot (typically generated by a statusLine command)
/// and displays 5-hour + 7-day usage bars.
private let planLimitTimeFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.locale = Locale(identifier: "en_US_POSIX")
    formatter.dateFormat = "HH:mm"
    return formatter
}()

private let planLimitDateTimeFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.locale = Locale(identifier: "en_US_POSIX")
    formatter.dateFormat = "dd MMM HH:mm"
    return formatter
}()

struct PlanLimitsCard: View {
    let snapshot: PlanLimitsSnapshot
    let diagnostics: PlanLimitsDiagnostics

    var body: some View {
        VStack(alignment: .leading, spacing: 5) {
            HStack(spacing: 6) {
                Text("Plan Limits")
                    .font(.system(size: 10, weight: .semibold))
                    .foregroundStyle(Color(nsColor: .secondaryLabelColor))
                    .tracking(0.5)
                    .textCase(.uppercase)

                Spacer()

                if snapshot.hasAnyData && diagnostics.state == .staleData {
                    Text("stale")
                        .font(.system(size: 10, weight: .medium))
                        .foregroundStyle(Color(nsColor: .systemOrange))
                }
            }
            .padding(.horizontal, 2)

            VStack(alignment: .leading, spacing: 0) {
                if snapshot.hasAnyData {
                    windowRow(title: "5-hour window", window: snapshot.fiveHour)

                    if snapshot.fiveHour.hasData && snapshot.sevenDay.hasData {
                        Divider()
                    }

                    windowRow(title: "7-day window", window: snapshot.sevenDay)

                    if let updatedAt = snapshot.updatedAt {
                        Divider()

                        HStack {
                            Text("Updated")
                                .font(.system(size: 10))
                                .foregroundStyle(Color(nsColor: .tertiaryLabelColor))
                            Spacer()
                            Text(Format.relativeTime(updatedAt))
                                .font(.system(size: 10, weight: .medium, design: .monospaced))
                                .foregroundStyle(Color(nsColor: .tertiaryLabelColor))
                        }
                        .padding(.horizontal, 12)
                        .padding(.vertical, 7)
                    }
                } else {
                    missingStateRow

                    Divider()

                    Text(diagnostics.message)
                        .font(.system(size: 10))
                        .foregroundStyle(Color(nsColor: .tertiaryLabelColor))
                        .padding(.horizontal, 12)
                        .padding(.vertical, 8)
                }
            }
            .background(.regularMaterial)
            .clipShape(RoundedRectangle(cornerRadius: 8))
            .overlay(
                RoundedRectangle(cornerRadius: 8)
                    .stroke(Color(nsColor: .separatorColor).opacity(0.4), lineWidth: 0.5)
            )
        }
    }

    private var missingStateRow: some View {
        HStack(spacing: 8) {
            Image(systemName: missingStateIcon)
                .font(.system(size: 13))
                .foregroundStyle(missingStateColor)
            Text(missingStateTitle)
                .font(.system(size: 12))
                .foregroundStyle(Color(nsColor: .secondaryLabelColor))
            Spacer()
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 10)
    }

    private var missingStateTitle: String {
        switch diagnostics.state {
        case .waitingForFirstResponse:
            return "Waiting for first API response"
        case .limitsUnavailableForSession:
            return "Plan limits unavailable in this session"
        case .statusLineNotRunning:
            return "statusLine source not running"
        case .staleData:
            return "Plan-limit data is stale"
        case .ready:
            return "No plan-limit data yet"
        }
    }

    private var missingStateIcon: String {
        switch diagnostics.state {
        case .waitingForFirstResponse:
            return "hourglass"
        case .limitsUnavailableForSession:
            return "nosign"
        case .statusLineNotRunning:
            return "bolt.slash.circle"
        case .staleData:
            return "clock.arrow.trianglehead.counterclockwise.rotate.90"
        case .ready:
            return "clock.badge.questionmark"
        }
    }

    private var missingStateColor: Color {
        switch diagnostics.state {
        case .statusLineNotRunning:
            return Color(nsColor: .systemRed)
        case .limitsUnavailableForSession, .staleData:
            return Color(nsColor: .systemOrange)
        case .waitingForFirstResponse, .ready:
            return Color(nsColor: .tertiaryLabelColor)
        }
    }

    @ViewBuilder
    private func windowRow(title: String, window: PlanLimitWindow) -> some View {
        if window.hasData {
            let fraction = window.progressFraction
            let pctText = window.usedPercentage.map { String(format: "%.0f%%", $0) } ?? "--"

            VStack(alignment: .leading, spacing: 6) {
                HStack {
                    HStack(spacing: 4) {
                        Text(title)
                            .font(.system(size: 11))
                            .foregroundStyle(Color(nsColor: .secondaryLabelColor))

                        if title == "7-day window" {
                            Text("All models")
                                .font(.system(size: 10, weight: .medium))
                                .foregroundStyle(Color(nsColor: .tertiaryLabelColor))
                        }
                    }
                    Spacer()
                    Text(pctText)
                        .font(.system(size: 11, weight: .semibold, design: .monospaced))
                        .foregroundStyle(progressColor(fraction))
                }

                GeometryReader { geo in
                    ZStack(alignment: .leading) {
                        RoundedRectangle(cornerRadius: 3)
                            .fill(Color(nsColor: .separatorColor).opacity(0.5))
                        RoundedRectangle(cornerRadius: 3)
                            .fill(progressColor(fraction))
                            .frame(width: max(6, geo.size.width * fraction))
                            .animation(.spring(response: 0.6, dampingFraction: 0.8), value: fraction)
                    }
                }
                .frame(height: 4)

                TimelineView(.periodic(from: .now, by: 60)) { _ in
                    HStack {
                        if let resetsAt = window.resetsAt {
                            Text("Resets in")
                                .font(.system(size: 10))
                                .foregroundStyle(Color(nsColor: .tertiaryLabelColor))
                            Spacer()
                            Text(resetDisplayText(title: title, until: resetsAt))
                                .font(.system(size: 10, weight: .medium, design: .monospaced))
                                .foregroundStyle(Color(nsColor: .tertiaryLabelColor))
                        } else {
                            Text("Reset time unavailable")
                                .font(.system(size: 10))
                                .foregroundStyle(Color(nsColor: .tertiaryLabelColor))
                            Spacer()
                        }
                    }
                }
            }
            .padding(.horizontal, 12)
            .padding(.vertical, 8)
        }
    }

    private func progressColor(_ fraction: Double) -> Color {
        if fraction < 0.70 { return Color(nsColor: .systemBlue) }
        if fraction < 0.90 { return Color(nsColor: .systemYellow) }
        return Color(nsColor: .systemRed)
    }

    private func relativeResetTime(until date: Date) -> String {
        let seconds = max(0, Int(date.timeIntervalSinceNow))
        let days = seconds / 86_400
        let hours = (seconds % 86_400) / 3_600
        let minutes = (seconds % 3_600) / 60

        if days > 0 {
            return "\(days)d \(hours)h"
        }
        return "\(hours)h \(minutes)m"
    }

    private func resetDisplayText(title: String, until date: Date) -> String {
        let countdown = relativeResetTime(until: date)
        return "\(countdown) · \(absoluteResetTime(title: title, date: date))"
    }

    private func absoluteResetTime(title: String, date: Date) -> String {
        if title == "5-hour window" {
            return planLimitTimeFormatter.string(from: date)
        }

        return planLimitDateTimeFormatter.string(from: date)
    }
}
